### ISSUE TITLE
icloud photo issue

### ISSUE THREAD

**Issue by sluggg** [kolbyjack/MMM-Wallpaper#41]
Module works as expected with default config options, as soon as I change to icloud with correct album ID nothing loads and terminal presents this error.
[30.06.2021 15:19.42.066] [ERROR] Whoops! There was an uncaught exception...
[30.06.2021 15:19.42.074] [ERROR] TypeError: photo.derivatives is not iterable
    at Class.processiCloudData (/home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js:343:31)
    at Class.processResponse (/home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js:224:21)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js:189:16)
    at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
[30.06.2021 15:19.42.081] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?

Thanks for the help 👍

**Comment by kolbyjack** [comment]
Sorry about that, got a little too aggressive replacing for..in with for..of, try latest master

**Comment by sluggg** [comment]
Brilliant! Thank you so much thats sorted it
