### ISSUE TITLE
2.1.6 update start with error "Cannot find module 'request'"

### ISSUE THREAD

**Issue by alexey-gamov** [kolbyjack/MMM-Wallpaper#43]
```
[02.07.2021 17:05.54.533] [LOG]   Starting MagicMirror: v2.16.0
[02.07.2021 17:05.54.552] [LOG]   Loading config ...
[02.07.2021 17:05.54.582] [LOG]   Loading module helpers ...
[02.07.2021 17:05.54.592] [LOG]   No helper found for module: alert.
[02.07.2021 17:05.55.276] [LOG]   Initializing new module helper ...
[02.07.2021 17:05.55.283] [LOG]   Module helper loaded: updatenotification
[02.07.2021 17:05.55.287] [LOG]   No helper found for module: clock.
[02.07.2021 17:05.55.825] [LOG]   Initializing new module helper ...
[02.07.2021 17:05.55.828] [LOG]   Module helper loaded: calendar
[02.07.2021 17:05.55.831] [LOG]   No helper found for module: weather.
[02.07.2021 17:05.55.912] [LOG]   Initializing new module helper ...
[02.07.2021 17:05.55.915] [LOG]   Module helper loaded: newsfeed
[02.07.2021 17:05.55.918] [LOG]   No helper found for module: mmm-worldclock.
[02.07.2021 17:05.55.931] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'
Require stack:
- /opt/magic_mirror/modules/MMM-Wallpaper/node_helper.js
- /opt/magic_mirror/js/app.js
- /opt/magic_mirror/js/electron.js
- /opt/magic_mirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
[02.07.2021 17:05.55.934] [LOG]   Loading module helpers ...
[02.07.2021 17:05.55.936] [LOG]   No helper found for module: alert.
[02.07.2021 17:05.55.938] [LOG]   Initializing new module helper ...
[02.07.2021 17:05.55.941] [LOG]   Module helper loaded: updatenotification
[02.07.2021 17:05.55.943] [LOG]   No helper found for module: clock.
[02.07.2021 17:05.55.946] [LOG]   Initializing new module helper ...
[02.07.2021 17:05.55.948] [LOG]   Module helper loaded: calendar
[02.07.2021 17:05.55.951] [LOG]   No helper found for module: weather.
[02.07.2021 17:05.55.953] [LOG]   Initializing new module helper ...
[02.07.2021 17:05.55.955] [LOG]   Module helper loaded: newsfeed
[02.07.2021 17:05.55.957] [LOG]   No helper found for module: mmm-worldclock.
[02.07.2021 17:05.55.967] [ERROR] App threw an error during load
[02.07.2021 17:05.55.973] [ERROR] Error: Cannot find module 'request'
Require stack:
- /opt/magic_mirror/modules/MMM-Wallpaper/node_helper.js
- /opt/magic_mirror/js/app.js
- /opt/magic_mirror/js/electron.js
- /opt/magic_mirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Function.Module._resolveFilename (/opt/magic_mirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-Wallpaper/node_helper.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
[02.07.2021 17:05.55.977] [ERROR] Whoops! There was an uncaught exception...
[02.07.2021 17:05.55.996] [ERROR] Error: Cannot find module 'request'
Require stack:
- /opt/magic_mirror/modules/MMM-Wallpaper/node_helper.js
- /opt/magic_mirror/js/app.js
- /opt/magic_mirror/js/electron.js
- /opt/magic_mirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Function.Module._resolveFilename (/opt/magic_mirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/magic_mirror/modules/MMM-Wallpaper/node_helper.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/magic_mirror/modules/MMM-Wallpaper/node_helper.js',
    '/opt/magic_mirror/js/app.js',
    '/opt/magic_mirror/js/electron.js',
    '/opt/magic_mirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[02.07.2021 17:05.56.000] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[02.07.2021 17:05.56.002] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```

**Comment by alexey-gamov** [comment]
Everything OK after disabling **MMM-Wallpaper**

**Comment by kolbyjack** [comment]
I've removed the `request` module dependency in latest master, please give it a try
