### ISSUE TITLE
Black screen - Module not found

### ISSUE THREAD

**Issue by unknownuser26** [kolbyjack/MMM-Wallpaper#50]
Hello,
I downloaded the plugin according to the instructions and added the example configuration in my configuration. Magicmirror does not start anymore and only shows a black screen

`[20.10.2021 23:23.57.056] [ERROR] [31mWARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'[39m
[31mRequire stack:[39m
[31m- /home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js[39m
[31m- /home/pi/MagicMirror/js/app.js[39m
[31m- /home/pi/MagicMirror/js/electron.js[39m
[31m- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js[39m
[31m- [39m
[20.10.2021 23:23.57.068] [ERROR] App threw an error during load
[20.10.2021 23:23.57.071] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
[20.10.2021 23:23.57.072] [ERROR] Whoops! There was an uncaught exception...
[20.10.2021 23:23.57.078] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[20.10.2021 23:23.57.079] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[20.10.2021 23:23.57.079] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues`

**Comment by kolbyjack** [comment]
The requests module was removed from the core magicmirror recently, so you'll need to
```
cd modules/MMM-Wallpaper
npm install
```
to install it
