### ISSUE TITLE
MODULE NOT FOUND Error

### ISSUE THREAD

**Issue by mgh151** [kolbyjack/MMM-Wallpaper#55]
Magic Mirror throws this error after start. 
--------------------------------------------------------------------------------
[28.11.2021 16:27.43.707] [LOG]   Loading module helpers ...
[28.11.2021 16:27.43.708] [LOG]   No helper found for module: alert.
[28.11.2021 16:27.43.709] [LOG]   Initializing new module helper ...
[28.11.2021 16:27.43.710] [LOG]   Module helper loaded: updatenotification
[28.11.2021 16:27.43.710] [LOG]   No helper found for module: clock.
[28.11.2021 16:27.43.711] [LOG]   Initializing new module helper ...
[28.11.2021 16:27.43.711] [LOG]   Module helper loaded: calendar
[28.11.2021 16:27.43.712] [LOG]   No helper found for module: MMM-MonthlyCalendar.
[28.11.2021 16:27.43.715] [ERROR] App threw an error during load
[28.11.2021 16:27.43.717] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
[28.11.2021 16:27.43.718] [ERROR] Whoops! There was an uncaught exception...
[28.11.2021 16:27.43.723] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
----------------------------------------------------------------------------------------------
MMM-Wallpaper does exist in the modules folder. 

Using the vanilla setup in the config.js file that is found in the Readme

**Comment by kolbyjack** [comment]
The `request` module was removed from the main magicmirror repo in 2.16, so now you need to run `npm install` in the `MMM-Wallpaper` directory.  I'll update the install instructions.

**Comment by mgh151** [comment]
Thanks, working great.
