### ISSUE TITLE
Newest pull > starting errors 

### ISSUE THREAD

**Issue by editwentyone** [kolbyjack/MMM-Wallpaper#77]
```
[21.08.2022 10:52.57.351] [ERROR] WARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: /home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js:153
      if (!searchTerm || searchTerm?.length === 0 || searchTerm === "") {
                                    ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at loadModule (/home/pi/MagicMirror/js/app.js:127:19)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:165:5)
    at /home/pi/MagicMirror/js/app.js:167:6
    at Class.loaded (/home/pi/MagicMirror/js/node_helper.js:18:3)
[21.08.2022 10:52.57.361] [ERROR] App threw an error during load
[21.08.2022 10:52.57.361] [ERROR] /home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js:153
      if (!searchTerm || searchTerm?.length === 0 || searchTerm === "") {
                                    ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at loadModule (/home/pi/MagicMirror/js/app.js:127:19)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:165:5)
    at /home/pi/MagicMirror/js/app.js:167:6
    at Class.loaded (/home/pi/MagicMirror/js/node_helper.js:18:3)
[21.08.2022 10:52.57.363] [ERROR] Whoops! There was an uncaught exception...
[21.08.2022 10:52.57.367] [ERROR] /home/pi/MagicMirror/modules/MMM-Wallpaper/node_helper.js:153
      if (!searchTerm || searchTerm?.length === 0 || searchTerm === "") {
                                    ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at loadModule (/home/pi/MagicMirror/js/app.js:127:19)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:165:5)
    at /home/pi/MagicMirror/js/app.js:167:6
    at Class.loaded (/home/pi/MagicMirror/js/node_helper.js:18:3)
[21.08.2022 10:52.57.368] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[21.08.2022 10:52.57.368] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```

**Comment by kolbyjack** [comment]
It appears that your version of node doesn't support the ?. operator. I've pushed a commit to remove them, give latest a try.

**Comment by editwentyone** [comment]
perfect, now its working after the git pull.

this is my node version: v16.16.0
